name: slp_parser
version: 0.0.2
homepage: https://github.com/simpleledger/slp-parser.dart
description: Parse Simple Ledger Protocol OP_RETURN data segments with ease!
dependencies:
    convert: ^2.1.1
dev_dependencies:
    test: ^1.14.2
environment:
    sdk: '>=1.20.1 <3.0.0'
